services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/app/data/
    env_file:
      - ./.env  
    environment:
      - UV_NATIVE_WHEELS=1  
    restart: unless-stopped